### ISSUE TITLE
Uploaded images have no cms thumbnail in assets admin

### ISSUE THREAD

**Issue by bumbus** [lekoala/silverstripe-filepond#1]
Maybe after uploading images `AssetAdmin::create()->generateThumbnails($image);` should be called to generate the thumb.

**Comment by lekoala** [comment]
That's a good idea ! I think it should also have a matching config flag to enable/disable this because maybe this is already done elsewhere (for my part, i do it in a file extension).

**Comment by lekoala** [comment]
Closed with https://github.com/lekoala/silverstripe-filepond/commit/2c727c7ff805cd368ed89ca3bb47ed3fc4219aff

**Comment by elkebe** [comment]
@lekoala I'm having trouble getting this to work - have set `enable_auto_thumbnails: true` in config, but CMS will show a blank white thumbnail until image is saved (publishing image without saving first does not generate thumbnail, but when explicitly saved in Asset Manager in CMS, thumbnail is generated). With `enable_auto_thumbnails: false` I get a blank blue thumbnail. Am using SS 4.8.

Have the following set up on MemberExtension:
```
private static $has_one = [
  'Photo' => Image::class
];
	
private static $owns = ['Photo'];
```

Any tips welcome!

**Comment by lekoala** [comment]
@elkebe it should work fine. Did you check if this part is running ? a simple die statement should help ;-) if the thumbnails are generated, it should work

    public function onAfterUpload()
    {
        if (File::config()->enable_auto_thumbnails) {
            AssetAdmin::create()->generateThumbnails($this->owner);
        }
    }

**Comment by lekoala** [comment]
@elkebe it seems that somehow the settings is never seen as true (and it wasn't working if you enabled chunking). Now it seems to be working, i've changed the settings to be on FilePondField instead

**Comment by elkebe** [comment]
@lekoala thanks for this. Have just updated to v1.2.1 - however something is not quite right as the FilePondFIeld is now displaying as a simple click-to-upload field (no longer a drag and drop field) and file does not get uploaded... was working fine in v1.1.1

Does the settings change require a different setup in config? I currently have the following:

```
SilverStripe\Assets\File:
  enable_auto_thumbnails: true
  extensions:
    - LeKoala\FilePond\FilePondFileExtension

LeKoala\FilePond\FilePondField:
  auto_clear_temp_folder: true
  enable_default_description: true
  enable_poster: true
```

**Comment by lekoala** [comment]
@elkebe should be fixed in 1.2.2 (an extra slash in the requirements)

SilverStripe\Assets\File:
  extensions:
    - LeKoala\FilePond\FilePondFileExtension

LeKoala\FilePond\FilePondField:
  enable_auto_thumbnails: true
  auto_clear_temp_folder: true
  enable_default_description: true
  enable_poster: true

should do the trick

**Comment by elkebe** [comment]
@lekoala thanks so much for your super quick responses on this. v1.2.2 displaying FielPondField correctly and uploads as expected, however there's still something funky going on, although this may be a problem with the Assets Admin itself? 
Image thumbnail appears in list view and image preview in File/assets manager, but not grid view or preview of has_one in CMS. Have attached screenshots for you (ignore the black boxes as they are just redacted names).

Another potential issue (but I haven't managed to test this thoroughly yet), is that multiple uploads from the same user (if saving to file name pattern of eg. FirstName-Surname.ext) display a different image preview in the FilePondField to the actual image in the $has_one - this only happened after about 4-5 profile images had been uploaded and may have been a weird configuration from my testing... will investigate further.

![Screen Shot 2021-06-30 at 10 38 55 PM](https://user-images.githubusercontent.com/31311851/123947984-1657cd80-d9f5-11eb-9f30-1d39aa2db687.png)
![Screen Shot 2021-06-30 at 10 39 06 PM](https://user-images.githubusercontent.com/31311851/123947642-b6612700-d9f4-11eb-920c-2d2b9dccdf11.png)
![Screen Shot 2021-06-30 at 10 38 38 PM](https://user-images.githubusercontent.com/31311851/123947965-1061ec80-d9f5-11eb-88ac-30d5c09133cc.png)
![Screen Shot 2021-06-30 at 10 39 20 PM](https://user-images.githubusercontent.com/31311851/123948002-1b1c8180-d9f5-11eb-8e74-9530e2709400.png)

**Comment by lekoala** [comment]
@elkebe i tested again on my end and i get the thumbnails. not sure what i could look for without a project having the actual issue to troubleshoot.
i would check the actual filesystem to see if the thumbnails are generated alongside after an upload. if yes, the issue is probably elsewhere.
and maybe indeed try to disable renaming pattern if that causes the issues or not. most of the time, i add the timestamp just in case in case of multiple uploads
