### ISSUE TITLE
Doesn't work with has_many or manymany relations

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-filepond#11]
The field doesn't seem to work with has_many or manymany relations.

It uploads the files, but only the first file is saved as relation to the dataobject.

Other files are not saved.

I see, that the browser tries to send an array with all file IDs, but PHP only retrieves one value of that in $_POST

Any ideas how to solve this?

**Comment by lekoala** [comment]
i will look into it, this seems like a regression that happened i don't know when :)

**Comment by lekoala** [comment]
should be fixed in https://github.com/lekoala/silverstripe-filepond/releases/tag/1.4.1

**Comment by lekoala** [comment]
closing this feel free to reopen if that didn't fix the issue
