### ISSUE TITLE
FilePond Instance

### ISSUE THREAD

**Issue by natino45** [lekoala/silverstripe-filepond#13]
Hi @lekoala

First of all, thank you for creating and maintaining this module. It has been extremely helpful for our project.

I am currently working on a project where I need to register additional plugins with an instance of FilePond. Could you please provide guidance on how to obtain the instance of FilePond to achieve this?

Specifically, I am looking to:

- Access the FilePond instance after it has been created.

- Register additional plugins dynamically.

Any code snippets or references to the relevant documentation would be great.

Best regards.

**Comment by lekoala** [comment]
hi @natino45 

thanks for the kind words

currently, it's not really feasible to do anything "after it's been created"; the whole logic is to load a fully featured custom element that can be configured as needed using php

so the way forward would be this

- disable global requirements enable_requirements
- build and include your own version of the custom element. see here to get started: https://github.com/lekoala/formidable-elements/blob/master/src/filepond-input.js
- if needed, extend the php class to take care of the additional config flags see getFilePondConfig
- work as usual

if you have a specific plugin that you think could be added globally, i'd be happy to support it if I think it would be useful for everyone

**Comment by natino45** [comment]
Great, Custom JS build works fine now.

Thank you.

**Comment by lekoala** [comment]
if you can share an example of how you did it that would be great :)
