### ISSUE TITLE
Suggestion: auto-determine chunk-size and if chunking is necessary

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-filepond#3]
It would be nice if the filepond field would:
- determine the max chunk size dynamically ([example](https://github.com/micschk/silverstripe-chunkeduploadfield/blob/master/code/ChunkedUploadField.php#L72))
- feed a treshold to JS from which uploads would have to be chunked (if FilePondJS supports this)
- OR maybe just always chunk uploads instead (may simplify code maintenance as we it can return to just one handler, and may also ease up server load etc with multiple smaller requests instead of one big upload(?))

Background/rationale
Currently chunkin is a (php level) configurable option. This means a dev would have to know the server environment a project will be ran on, on beforehand to activate chunking. This is often not the case, eg when developing a re-usable module but also when moving existing projects to a different server/environment etc. 

Activating chunkin later would currently also require editing the project-code or even the code of another module utilizing FilePond. Not sure if the default 5MB chunk size comes from FilePondJS or if this module sets it, but the default max upload size of an unconfigured PHP is often even just 2MB.

**Comment by lekoala** [comment]
I made a couple of changes in https://github.com/lekoala/silverstripe-filepond/commit/939c3ec9faf4110c704998d7a4bb5ad0e77ebe25

you can set chunk as the default option. chunk size is computed automatically. still need to tweak a few things (like default validation size if chunking is applied, how to determine what is the "reasonable" max size)

**Comment by micschk** [comment]
@lekoala what do you mean with "how to determine what is the reasonable max size"?
Did you notice [the example](https://github.com/micschk/silverstripe-chunkeduploadfield/blob/master/code/ChunkedUploadField.php#L72)? That's how I used to determine the reasonable max [chunk] size (eg 90% of the max upload size).

**Comment by lekoala** [comment]
@micschk no i mean let's say you have a server that is by default limited to 10 mb. You don't expect users to upload anything larger. if you enable chunking, they can suddenly upload very large files so maybe it's still a good thing to make this "opt in". Currently i simply removed the limit and you have to set a limit yourself, which is fine i guess since you are expected to know what you are doing if you enable chunking by default on all uploaders

**Comment by micschk** [comment]
Oh, yes wel basically it is always possible to upload large amounts of data to a server. Only the max amount of data per request is restricted, so if you have a 'max 5MB' regular uploadfield I can in theory still upload 1000 times 5MB. 
I think there's two 'parts' to this issue; 
1. the transfer mechanism (to chunk or not to chunk)
2. the validation (on finishing the upload)

The chunking could be considered a given, as that simply allows uploading large files. Then there's the validation part, that's where this issue should be fixed. I think usually the webserver & PHP layers take care of the low-level stuff like writing the uploaded data to a temp file and then a field like UploadField handles the validation of this written data.

This is comparable to what's happening now with chunked filepond. So if you set a max size on a filepond field instance, it should just return an error once the total size of uploaded chunks has become larger than this maximum.

One extra thing which is actually a benefit of the chunked uploading mechanism is that it might already be possible to return an error before finishing all chunks, namely from the 'handle chunk' function (not sure what's its actual name).

**Comment by lekoala** [comment]
> This is comparable to what's happening now with chunked filepond. So if you set a max size on a filepond field instance, it should just return an error once the total size of uploaded chunks has become larger than this maximum.

that's a good one, will look into it :)

**Comment by lekoala** [comment]
closed with https://github.com/lekoala/silverstripe-filepond/commit/f2269503448e8ef8fb0f5d6d0a9384edebe7c4bb
