### ISSUE TITLE
Note: just archived micschk/silverstripe-chunkeduploadfield and recommended filepond instead

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-filepond#4]
REAME on micschk/silverstripe-chunkeduploadfield now reads:<br>
<img width="604" alt="Screenshot 2021-06-25 at 16 21 26" src="https://user-images.githubusercontent.com/1005986/123439015-9800c300-d5d1-11eb-95b6-5b1cb4529bac.png">

Abandoned & recommended filepond via packagist as well.

**Comment by lekoala** [comment]
@micschk  thanks !

as a side note, i have also this one on my radar https://github.com/codem/silverstripe-damn-fine-uploader maybe there are some good things there as well

**Comment by micschk** [comment]
> as a side note, i have also this one on my radar https://github.com/codem/silverstripe-damn-fine-uploader maybe there are some good things there as well

That one seems to be front-end only though, solves a different problem. But it may indeed contain some 'adoptable' parts :-)

From the README:
> This module is not intended for use in the Silverstripe administration area, use the standard UploadField for that.
