### ISSUE TITLE
Switch to npm/yarn for JS dependencies

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-filepond#6]
JS dependencies are now included from CDN and a script is included to download JS dependencies from locally(?)
I there a reason not to use npm/yarn for managing JS dependencies? (PR coming up)

**Comment by lekoala** [comment]
@micschk not really ;-) it's simply a matter of not including more files than necessary. If we expand the scope to support things like all the plugins and everything then it would make sense.

**Comment by lekoala** [comment]
so this took another route. I added a bundle you can use instead. Otherwise i recommended ignoring requirements altogether and bundle your own resources (taking other modules into account as well)
