### ISSUE TITLE
Field validator (set)AllowedMaxFileSize not passed to filepond JS config

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-filepond#8]
In CFStreamVideo's StreamVideoObject, filepond is set to chunk uploads and allow files which are up to 1GB (which is larger than the server default max upload of 32MB):

```PHP
$Video = new FilePondField("Video")
$Video->setChunkUploads(true);
$Video->getValidator()->setAllowedMaxFileSize(['*' => '1GB']);
```
Dragging a video of 35MB onto filepond now still results in:
<img width="162" alt="Screenshot 2021-07-04 at 13 33 55" src="https://user-images.githubusercontent.com/1005986/124384695-cae23f80-dcd2-11eb-87a2-c67d04e95683.png">

Only if we also manually set maxFileSize for filepond JS config (supplementary to validator's setAllowedMaxFileSize), we can upload larger files:
```PHP
$Video->addFilePondConfig('maxFileSize', Convert::memstring2bytes('1GB'));
```

**Comment by lekoala** [comment]
It seems that filepond only reads KB and MB notation and not GB^^ fixed in https://github.com/lekoala/silverstripe-filepond/commit/d62465d71977bf072987aeeb976b1690c2e40b23
